# Generated by Django 5.0.1 on 2024-02-24 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_alter_user_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=255)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.user')),
            ],
        ),
        migrations.CreateModel(
            name='SectionName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.TextField()),
                ('photo_content', models.ImageField(upload_to='images/<django.db.models.fields.related.ForeignKey>/')),
                ('file_content', models.FileField(upload_to='files/<django.db.models.fields.related.ForeignKey>/')),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.section')),
            ],
        ),
    ]
