# Generated by Django 5.0.1 on 2024-02-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_rename_sectionname_sectionitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionitem',
            name='item_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sectionitem',
            name='file_content',
            field=models.FileField(blank=True, upload_to='files/<django.db.models.fields.related.ForeignKey>/'),
        ),
        migrations.AlterField(
            model_name='sectionitem',
            name='photo_content',
            field=models.ImageField(blank=True, upload_to='images/<django.db.models.fields.related.ForeignKey>/'),
        ),
    ]
