# Generated by Django 5.0.1 on 2024-02-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_sectionitem_item_name_alter_sectionitem_file_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionitem',
            name='text_content',
            field=models.TextField(blank=True),
        ),
    ]
