# Generated by Django 5.0.1 on 2024-02-24 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_rename_user_id_section_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionitem',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.section', unique=True),
        ),
    ]
